const CACHE='taptocity-story-20261008d-residents';
const SHELL=['./assets/illustrated/underground-icons.webp','./assets/illustrated/survivors-silhouettes.webp?v=3','./assets/illustrated/crows-kids.webp','./assets/illustrated/residents.webp','./assets/illustrated/player-faceless.webp','./assets/illustrated/story-1.webp?v=1','./assets/illustrated/story-2.webp?v=1','./assets/illustrated/story-3.webp?v=1','./assets/illustrated/world-panorama.webp','./assets/illustrated/founder-expressions.webp','./','./index.html','./chapter-design.js?v=20261008-res2','./assets/illustrated/regional-npcs.webp','./assets/illustrated/module-upgrades.webp','./assets/illustrated/ash-foes.webp','./assets/illustrated/world-scenes.webp','./settlement.js?v=20261006-petscale','./assets/illustrated/settlement-props.webp','./assets/illustrated/companions.webp','./people.js?v=20261001-people','./manifest.webmanifest','./cloud.js','./cloud-config.js','./fonts/ttc-sans.woff2','./icons/icon-192.png?v=2','./icons/icon-512.png?v=2','./design.css?v=20261004-anonymous','./qa.css?v=20261008a','./story-art.js?v=20261005e','./music.js?v=20261006a','./design.js?v=20261008-res2','./assets/illustrated/survivors-signals.webp','./assets/illustrated/survivors-neighbors.webp','./assets/illustrated/shelters.webp','./assets/illustrated/survivors-founders.webp','./assets/illustrated/modules.webp','./assets/illustrated/survivors-scouts.webp','./assets/illustrated/survivors-frontier.webp','./assets/illustrated/radio.webp','./assets/illustrated/exploration-sites.webp','./assets/illustrated/landmarks.webp'];
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE).then(c=>c.addAll(SHELL)).then(()=>self.skipWaiting()));});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(ks=>Promise.all(ks.filter(k=>k.startsWith('taptocity-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()));});
self.addEventListener('fetch',e=>{const r=e.request;if(r.method!=='GET')return;
 const u=new URL(r.url);
 if(u.origin!==location.origin)return;
 if(u.origin===location.origin&&(r.mode==='navigate'||u.pathname.endsWith('/')||u.pathname.endsWith('index.html'))){
  e.respondWith(fetch(r.url,{cache:'no-cache',credentials:'same-origin'}).then(res=>{if(!res.ok)throw new Error('Navigation unavailable');const c=res.clone();e.waitUntil(caches.open(CACHE).then(x=>x.put('./index.html',c)));return res;}).catch(()=>caches.match('./index.html')));return;}
 e.respondWith(caches.match(r).then(hit=>hit||fetch(r).then(res=>{if(res.ok||res.type==='opaque'){const c=res.clone();e.waitUntil(caches.open(CACHE).then(x=>x.put(r,c)));}return res;}).catch(()=>hit)));});

